# Generated by Django 3.2.9 on 2021-11-17 18:07
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0002_category_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="username",
            field=models.CharField(default="Unknown", max_length=25, unique=True, verbose_name="Username"),
        ),
    ]
