# Generated by Django 3.2.9 on 2021-11-17 18:33
import django.db.models.deletion
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0003_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="post",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="comments",
                to="main.post",
                verbose_name="Under post",
            ),
        ),
    ]
