# Generated by Django 3.2.9 on 2021-11-17 23:06
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0004_alter_comment_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="categories",
            field=models.ManyToManyField(
                blank=True,
                db_table="post_category",
                related_name="categories",
                to="main.Category",
                verbose_name="Post categories",
            ),
        ),
    ]
